# If not running interactively, don't do anything (leave this at the top of this file)
[[ $- != *i* ]] && return

# All the default Omarchy aliases and functions
# (don't mess with these directly, just overwrite them here!)
source ~/.local/share/omarchy/default/bash/rc

# Add your own exports, aliases, and functions here.
export PATH="$HOME/.local/bin:$PATH"

# Make an alias for invoking commands you use constantly
# alias p='python'
alias claude-yolo='claude --dangerously-skip-permissions'

# Amp CLI
export PATH="/home/siso/.amp/bin:$PATH"

# Golang
export PATH="$PATH:$HOME/go/bin"

. "$HOME/.local/share/../bin/env"

# Added by LM Studio CLI (lms)
export PATH="$PATH:/home/siso/.lmstudio/bin"
# End of LM Studio CLI section

