# Extra autostart processes
# exec-once = uwsm-app -- my-service

# ActivityWatch
exec-once = uwsm-app -- aw-qt
exec-once = uwsm-app -- aw-watcher-window-hyprland
exec-once = uwsm-app -- aw-watcher-media-player
