# Force MATLAB onto the 1.0-scale monitor (no blur/pixelation)
windowrulev2 = monitor HDMI-A-1, class:^(MATLAB.*)$
windowrulev2 = workspace 5, class:^(MATLAB.*)$
#windowrulev2 = float, class:^(MATLAB.*)$

